wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1634804409
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 1
      4: 3.9.5
      5: 0.12.2
      8:
      - 5
batch_size:
  desc: null
  value: 16
beta:
  desc: null
  value: 1.0
data_name:
  desc: null
  value: Corr
dropout:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 200
gamma:
  desc: null
  value: 0.0
hidden_dim:
  desc: null
  value: 16
latent_dim:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
m_noise:
  desc: null
  value: 10
model_type:
  desc: null
  value: conv_mlp
n_graphs:
  desc: null
  value: 200
n_noise:
  desc: null
  value: 0
p2_prior:
  desc: null
  value: 1.0
prior_family:
  desc: null
  value: Normal
wandb:
  desc: null
  value: 1
